# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/ferreteriaeldesvare?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=74590548.Vp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# IMPORTANTE: no borra las tablas existentes
spring.jpa.hibernate.ddl-auto=update

# mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# THYMELEAF
# ===============================

spring.thymeleaf.cache=false


# ===============================
# SERVIDOR
# ===============================

server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always